include("preprocess_multidualmot.jl")
include("anlz_mot_loading_421_runner.jl")
include("anlz_mot_loading_626_runner.jl")
include("anlz_cmot_lifetime_runner.jl")
include("anlz_mot_lifetime_runner.jl")
include("anlz_isotope_pair_comparison_runner.jl")
include("anlz_odt_ib_runner.jl")
include("../helpers/make_multi_dual_mot_table.jl")
isinteractive() || main_multi_dual_mot_table(String[])
