include(joinpath(@__DIR__, "preprocess_multidualmot.jl"))
include(joinpath(@__DIR__, "anlz_mot_loading_421_runner.jl"))
include(joinpath(@__DIR__, "anlz_mot_loading_626_runner.jl"))
include(joinpath(@__DIR__, "anlz_mot_loading_balance_runner.jl"))
include(joinpath(@__DIR__, "anlz_cmot_lifetime_runner.jl"))
include(joinpath(@__DIR__, "anlz_mot_lifetime_runner.jl"))
include(joinpath(@__DIR__, "anlz_isotope_pair_comparison_runner.jl"))
include(joinpath(@__DIR__, "anlz_lifetime_pair_comparison.jl"))
include(joinpath(@__DIR__, "anlz_odt_ib_runner.jl"))
include(joinpath(@__DIR__, "anlz_odt_cmot_comparison.jl"))
main_multi_dual_mot_table(["--formats=svg,png,one"])